WIP, unmet dependencies
error: Failed build dependencies:
	perl(Devel::StackTrace) >= 1.23
	perl(Devel::StackTrace::AsHTML) >= 0.11
	perl(Filesys::Notify::Simple)
	perl(Test::TCP) >= 0.11
	perl(Test::Requires)